"""empty message

Revision ID: 55e249b3117b
Revises: 
Create Date: 2017-01-09 15:21:22.301694

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '55e249b3117b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipments',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('users',
                    sa.Column('sso', sa.Integer(), nullable=False),
                    sa.Column('last_name', sa.String(length=64), nullable=False),
                    sa.Column('first_name', sa.String(length=64), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=False, default=True),
                    sa.Column('password_hash', sa.String(length=128), nullable=True),
                    sa.PrimaryKeyConstraint('sso')
                    )
    op.create_table('records',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('sso', sa.Integer(), nullable=True),
                    sa.Column('equipment', sa.Integer(), nullable=True),
                    sa.Column('record_type', sa.String(), nullable=False),
                    sa.ForeignKeyConstraint(['equipment'], ['equipments.id'], ),
                    sa.ForeignKeyConstraint(['sso'], ['users.sso'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('records')
    op.drop_table('users')
    op.drop_table('equipments')
    # ### end Alembic commands ###
