"""empty message

Revision ID: c1368071c083
Revises: c93c87ef175b
Create Date: 2017-01-23 13:41:48.885554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1368071c083'
down_revision = 'c93c87ef175b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipments', sa.Column('accuracy', sa.String(length=20), nullable=True))
    op.add_column('equipments', sa.Column('brand', sa.String(length=64), nullable=True))
    op.add_column('equipments', sa.Column('calibration_due', sa.Date(), nullable=True))
    op.add_column('equipments', sa.Column('category', sa.String(length=20), nullable=True))
    op.add_column('equipments', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('equipments', sa.Column('equipment_id', sa.String(length=20), nullable=True))
    op.add_column('equipments', sa.Column('equipment_range', sa.String(length=20), nullable=True))
    op.add_column('equipments', sa.Column('status', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('equipments', 'status')
    op.drop_column('equipments', 'equipment_range')
    op.drop_column('equipments', 'equipment_id')
    op.drop_column('equipments', 'description')
    op.drop_column('equipments', 'category')
    op.drop_column('equipments', 'calibration_due')
    op.drop_column('equipments', 'brand')
    op.drop_column('equipments', 'accuracy')
    # ### end Alembic commands ###
